<html xmlns="http://www.w3.org/1999/xhtml" xmlns="http://www.w3.org/1999/xhtml">
  <head>
<!-- NAME: 1 COLUMN -->
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>EESoc - Imperial College London</title>
<!--[if gte mso 6]>
        <style>
            table.mcnFollowContent {width:100% !important;}
            table.mcnShareContent {width:100% !important;}
        </style>
        <![endif]-->
  </head>
  <body leftmargin="0" marginwidth="0" topmargin="0" marginheight="0" offset="0" style="margin: 0;padding: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;background-color: #F0F0FA;height: 100% !important;width: 100% !important;font-family: HelveticaNeue-Light, &quot;Helvetica Neue Light&quot;, &quot;Helvetica Neue&quot;, &quot;Trade Gothic W01 Light&quot;, Helvetica, Arial, &quot;Lucida Grande&quot;, sans-serif">
        <center>
            <table align="center" border="0" cellpadding="0" cellspacing="0" height="100%" width="100%" id="bodyTable" style="border-collapse: collapse;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;margin: 0;padding: 0;background-color: #F0F0FA;height: 100% !important;width: 100% !important;background-image: url(https://eesoc.com/assets/email/20131008/bg.png);background-position: top right;background-repeat: no-repeat;font-family: HelveticaNeue-Light, &quot;Helvetica Neue Light&quot;, &quot;Helvetica Neue&quot;, &quot;Trade Gothic W01 Light&quot;, Helvetica, Arial, &quot;Lucida Grande&quot;, sans-serif"><tr><td align="center" valign="top" id="bodyCell" style="mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;margin: 0;padding: 30px 20px 20px;border-top: 0;height: 100% !important;width: 100% !important;font-family: HelveticaNeue-Light, &quot;Helvetica Neue Light&quot;, &quot;Helvetica Neue&quot;, &quot;Trade Gothic W01 Light&quot;, Helvetica, Arial, &quot;Lucida Grande&quot;, sans-serif">
                        <!-- BEGIN TEMPLATE // -->
                        <table border="0" cellpadding="0" cellspacing="0" width="600" id="templateContainer" style="border-collapse: collapse;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;border: thin solid #ccc"><tr><td align="center" valign="top" style="mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%">
                                    <!-- BEGIN PREHEADER // -->
                                    <table border="0" cellpadding="0" cellspacing="0" width="600" id="templatePreheader" style="border-collapse: collapse;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;background-color: #FFF;border-top: 0;border-bottom: 0"><tr><td valign="top" class="preheaderContainer" style="padding-top: 9px;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%"><table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnTextBlock" style="border-collapse: collapse;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%"><tbody class="mcnTextBlockOuter"><tr><td valign="top" class="mcnTextBlockInner" style="mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%">

                <table align="left" border="0" cellpadding="0" cellspacing="0" width="600" class="mcnTextContentContainer" style="border-collapse: collapse;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%"><tbody><tr><td valign="top" class="mcnTextContent" style="padding-top: 9px;padding-left: 18px;padding-bottom: 9px;padding-right: 0;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #606060;font-family: HelveticaNeue-Light, &quot;Helvetica Neue Light&quot;, &quot;Helvetica Neue&quot;, &quot;Trade Gothic W01 Light&quot;, Helvetica, Arial, &quot;Lucida Grande&quot;, sans-serif;font-size: 11px;line-height: 125%;text-align: left">
                            EESoc, the Society for all students of the Department of Electrical &amp; Electronic Egineering at Imperial College London
                        </td>
                    </tr></tbody></table><table align="right" border="0" cellpadding="0" cellspacing="0" width="197" class="mcnTextContentContainer" style="border-collapse: collapse;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%"><tbody><tr><td valign="top" class="mcnTextContent" style="padding-top: 9px;padding-right: 18px;padding-bottom: 9px;padding-left: 0;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #606060;font-family: HelveticaNeue-Light, &quot;Helvetica Neue Light&quot;, &quot;Helvetica Neue&quot;, &quot;Trade Gothic W01 Light&quot;, Helvetica, Arial, &quot;Lucida Grande&quot;, sans-serif;font-size: 11px;line-height: 125%;text-align: left">
                        </td>
                    </tr></tbody></table></td>
        </tr></tbody></table></td>
                                        </tr></table><!-- // END PREHEADER --></td>
                            </tr><tr><td align="center" valign="top" style="mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%">
                                    <!-- BEGIN HEADER // -->
                                    <table border="0" cellpadding="0" cellspacing="0" width="600" id="templateHeader" style="border-collapse: collapse;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;background-color: #FFF;border-top: 0;border-bottom: 0"><tr><td valign="top" class="headerContainer" style="mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%"><table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnImageBlock" style="border-collapse: collapse;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%"><tbody class="mcnImageBlockOuter"><tr><td valign="top" style="padding: 9px;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%" class="mcnImageBlockInner">
                    <table align="left" width="100%" border="0" cellpadding="0" cellspacing="0" class="mcnImageContentContainer" style="border-collapse: collapse;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%"><tbody><tr><td class="mcnImageContent" align="center" valign="top" style="padding-right: 9px;padding-left: 9px;padding-top: 0;padding-bottom: 0;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%">


                                        <a href="http://bit.ly/19yZzh9" style="word-wrap: break-word;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%"><img align="center" alt="" src="https://eesoc.com/assets/email/20131008/logo.jpg" width="400" style="max-width: 400px;padding-bottom: 0;display: inline !important;vertical-align: bottom;border: 0;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic" class="mcnImage" /></a>


                            </td>
                        </tr></tbody></table></td>
            </tr></tbody></table></td>
                                        </tr></table><!-- // END HEADER --></td>
                            </tr><tr><td align="center" valign="top" style="mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%">
                                    <!-- BEGIN BODY // -->
                                    <table border="0" cellpadding="0" cellspacing="0" width="600" id="templateBody" style="border-collapse: collapse;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;background-color: #FFF;border-top: 0;border-bottom: 0"><tr><td valign="top" class="bodyContainer" style="mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%"><table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnTextBlock" style="border-collapse: collapse;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%"><tbody class="mcnTextBlockOuter"><tr><td valign="top" class="mcnTextBlockInner" style="mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%">

                <table align="left" border="0" cellpadding="0" cellspacing="0" width="600" class="mcnTextContentContainer" style="border-collapse: collapse;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%"><tbody><tr><td valign="top" class="mcnTextContent" style="padding-top: 9px;padding-right: 18px;padding-bottom: 9px;padding-left: 18px;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #606060;font-family: HelveticaNeue-Light, &quot;Helvetica Neue Light&quot;, &quot;Helvetica Neue&quot;, &quot;Trade Gothic W01 Light&quot;, Helvetica, Arial, &quot;Lucida Grande&quot;, sans-serif;font-size: 15px;line-height: 150%;text-align: left">


<p style="margin: 1em 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #606060;font-family: HelveticaNeue-Light, &quot;Helvetica Neue Light&quot;, &quot;Helvetica Neue&quot;, &quot;Trade Gothic W01 Light&quot;, Helvetica, Arial, &quot;Lucida Grande&quot;, sans-serif;font-size: 14px;line-height: 150%;text-align: left">Dear All,</p>

<p style="margin: 1em 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #606060;font-family: HelveticaNeue-Light, &quot;Helvetica Neue Light&quot;, &quot;Helvetica Neue&quot;, &quot;Trade Gothic W01 Light&quot;, Helvetica, Arial, &quot;Lucida Grande&quot;, sans-serif;font-size: 14px;line-height: 150%;text-align: left">I trust you have had a wonderful first week at Imperial! If you're new, I'm sure between the departments, halls and societies that you've been taken care of. If you are returning, I hope London has retained its charm﻿!</p>

<p style="margin: 1em 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #606060;font-family: HelveticaNeue-Light, &quot;Helvetica Neue Light&quot;, &quot;Helvetica Neue&quot;, &quot;Trade Gothic W01 Light&quot;, Helvetica, Arial, &quot;Lucida Grande&quot;, sans-serif;font-size: 14px;line-height: 150%;text-align: left">TL;DR? Here's an update on last week and next week<br />
- We've had a great week running EESoc events last week!<br />
- Winner of Instagram #EESoc competition!<br />
- Meet the Team<br />
- Lockers on sale from Monday 14 October<br />
- Book Sale on Wednesday 16 October, 12-14<br />
- Updates from two of our sponsors, BP and Deutsche Bank</p>

<h3 style="margin: 0;padding: 0;display: block;font-family: HelveticaNeue-Light, &quot;Helvetica Neue Light&quot;, &quot;Helvetica Neue&quot;, &quot;Trade Gothic W01 Light&quot;, Helvetica, Arial, &quot;Lucida Grande&quot;, sans-serif;font-size: 22px;font-style: normal;font-weight: 300;line-height: 125%;letter-spacing: -0.5px;text-align: left;color: #606060 !important"><a href="http://bit.ly/1a9ETgL" style="word-wrap: break-word;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #6DC6DD;font-weight: normal;text-decoration: underline">#EESoc</a> Freshers' Week Photos</h3>

<p style="margin: 1em 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #606060;font-family: HelveticaNeue-Light, &quot;Helvetica Neue Light&quot;, &quot;Helvetica Neue&quot;, &quot;Trade Gothic W01 Light&quot;, Helvetica, Arial, &quot;Lucida Grande&quot;, sans-serif;font-size: 14px;line-height: 150%;text-align: left"><a href="http://bit.ly/1bYcmy4" style="word-wrap: break-word;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #6DC6DD;font-weight: normal;text-decoration: underline"><img src="https://eesoc.com/assets/email/uploads/email_1_5.jpg" width="550" style="width: 550px;border: 0;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;height: auto !important" /></a></p>

<p style="margin: 1em 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #606060;font-family: HelveticaNeue-Light, &quot;Helvetica Neue Light&quot;, &quot;Helvetica Neue&quot;, &quot;Trade Gothic W01 Light&quot;, Helvetica, Arial, &quot;Lucida Grande&quot;, sans-serif;font-size: 14px;line-height: 150%;text-align: left">Congratulations to the Heaffey-Zhang family for this lovely photo spelling out EESoc. You've won EESoc t-shirts!</p>

<p style="margin: 1em 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #606060;font-family: HelveticaNeue-Light, &quot;Helvetica Neue Light&quot;, &quot;Helvetica Neue&quot;, &quot;Trade Gothic W01 Light&quot;, Helvetica, Arial, &quot;Lucida Grande&quot;, sans-serif;font-size: 14px;line-height: 150%;text-align: left">Second place goes to <a href="http://bit.ly/1fYSjEQ" style="word-wrap: break-word;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #6DC6DD;font-weight: normal;text-decoration: underline">Helen Root's video of Angry Birds Icebreaker projects</a>.</p>
<p style="margin: 1em 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #606060;font-family: HelveticaNeue-Light, &quot;Helvetica Neue Light&quot;, &quot;Helvetica Neue&quot;, &quot;Trade Gothic W01 Light&quot;, Helvetica, Arial, &quot;Lucida Grande&quot;, sans-serif;font-size: 14px;line-height: 150%;text-align: left">And taking third place home, <a href="http://bit.ly/1gpr7g2" style="word-wrap: break-word;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #6DC6DD;font-weight: normal;text-decoration: underline">some Freshers' and their parents go to Scoop</a>!</p>

<table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnDividerBlock" style="border-collapse: collapse;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%"><tbody class="mcnDividerBlockOuter"><tr><td class="mcnDividerBlockInner" style="padding: 10px 18px;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%">
                <table class="mcnDividerContent" border="0" cellpadding="0" cellspacing="0" width="100%" style="border-top-width: 1px;border-top-style: solid;border-top-color: #CCC;border-collapse: collapse;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%"><tbody><tr><td style="mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%">
                            <span></span>
                        </td>
                    </tr></tbody></table></td>
        </tr></tbody></table><h3 style="margin: 0;padding: 0;display: block;font-family: HelveticaNeue-Light, &quot;Helvetica Neue Light&quot;, &quot;Helvetica Neue&quot;, &quot;Trade Gothic W01 Light&quot;, Helvetica, Arial, &quot;Lucida Grande&quot;, sans-serif;font-size: 22px;font-style: normal;font-weight: 300;line-height: 125%;letter-spacing: -0.5px;text-align: left;color: #606060 !important">Meet the Team and see what we have planned</h3>
<p style="margin: 1em 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #606060;font-family: HelveticaNeue-Light, &quot;Helvetica Neue Light&quot;, &quot;Helvetica Neue&quot;, &quot;Trade Gothic W01 Light&quot;, Helvetica, Arial, &quot;Lucida Grande&quot;, sans-serif;font-size: 14px;line-height: 150%;text-align: left">Remember that video we showed Freshers' and parents on the first day? Yup. That very cheesy one. <a href="http://bit.ly/16wDIdD" style="word-wrap: break-word;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #6DC6DD;font-weight: normal;text-decoration: underline">Watch it again, and laugh!</a></p>

<p style="margin: 1em 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #606060;font-family: HelveticaNeue-Light, &quot;Helvetica Neue Light&quot;, &quot;Helvetica Neue&quot;, &quot;Trade Gothic W01 Light&quot;, Helvetica, Arial, &quot;Lucida Grande&quot;, sans-serif;font-size: 14px;line-height: 150%;text-align: left">See what we have planned in what will be an action packed Autumn term. Watch the <a href="http://bit.ly/19yPDdj" style="word-wrap: break-word;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #6DC6DD;font-weight: normal;text-decoration: underline">launch video</a>:</p>

<p style="margin: 1em 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #606060;font-family: HelveticaNeue-Light, &quot;Helvetica Neue Light&quot;, &quot;Helvetica Neue&quot;, &quot;Trade Gothic W01 Light&quot;, Helvetica, Arial, &quot;Lucida Grande&quot;, sans-serif;font-size: 14px;line-height: 150%;text-align: left"><a href="http://bit.ly/1bGxPPk" style="word-wrap: break-word;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #6DC6DD;font-weight: normal;text-decoration: underline"><img src="https://eesoc.com/assets/email/uploads/email_1_1.jpg" width="550" style="width: 550px;border: 0;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;height: auto !important" /></a></p>

<table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnDividerBlock" style="border-collapse: collapse;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%"><tbody class="mcnDividerBlockOuter"><tr><td class="mcnDividerBlockInner" style="padding: 10px 18px;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%">
                <table class="mcnDividerContent" border="0" cellpadding="0" cellspacing="0" width="100%" style="border-top-width: 1px;border-top-style: solid;border-top-color: #CCC;border-collapse: collapse;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%"><tbody><tr><td style="mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%">
                            <span></span>
                        </td>
                    </tr></tbody></table></td>
        </tr></tbody></table><h3 style="margin: 0;padding: 0;display: block;font-family: HelveticaNeue-Light, &quot;Helvetica Neue Light&quot;, &quot;Helvetica Neue&quot;, &quot;Trade Gothic W01 Light&quot;, Helvetica, Arial, &quot;Lucida Grande&quot;, sans-serif;font-size: 22px;font-style: normal;font-weight: 300;line-height: 125%;letter-spacing: -0.5px;text-align: left;color: #606060 !important">Locker Sale</h3>

<p style="margin: 1em 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #606060;font-family: HelveticaNeue-Light, &quot;Helvetica Neue Light&quot;, &quot;Helvetica Neue&quot;, &quot;Trade Gothic W01 Light&quot;, Helvetica, Arial, &quot;Lucida Grande&quot;, sans-serif;font-size: 14px;line-height: 150%;text-align: left">As you may know, we have three floors of lockers for you, our members. These can be rented out for £5 for the year. Interested? Lockers will go on sale online on Monday (14 October) at <strong>9:00 AM</strong>. We will send out an email about this once the lockers are ready to be sold.</p>

<p style="margin: 1em 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #606060;font-family: HelveticaNeue-Light, &quot;Helvetica Neue Light&quot;, &quot;Helvetica Neue&quot;, &quot;Trade Gothic W01 Light&quot;, Helvetica, Arial, &quot;Lucida Grande&quot;, sans-serif;font-size: 14px;line-height: 150%;text-align: left">Own a locker from last year? <strong>Please vacate your locker by Monday</strong>, as any locked locker will be opened and emptied after this date. Send us an email if you cannot empty your locker by then. Under certain circumstances, we will also let you keep your locker from last year; please <a href="mailto:eesoc@imperial.ac.uk" style="word-wrap: break-word;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #6DC6DD;font-weight: normal;text-decoration: underline">let us know</a>.</p>

<table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnDividerBlock" style="border-collapse: collapse;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%"><tbody class="mcnDividerBlockOuter"><tr><td class="mcnDividerBlockInner" style="padding: 10px 18px;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%">
                <table class="mcnDividerContent" border="0" cellpadding="0" cellspacing="0" width="100%" style="border-top-width: 1px;border-top-style: solid;border-top-color: #CCC;border-collapse: collapse;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%"><tbody><tr><td style="mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%">
                            <span></span>
                        </td>
                    </tr></tbody></table></td>
        </tr></tbody></table><h3 style="margin: 0;padding: 0;display: block;font-family: HelveticaNeue-Light, &quot;Helvetica Neue Light&quot;, &quot;Helvetica Neue&quot;, &quot;Trade Gothic W01 Light&quot;, Helvetica, Arial, &quot;Lucida Grande&quot;, sans-serif;font-size: 22px;font-style: normal;font-weight: 300;line-height: 125%;letter-spacing: -0.5px;text-align: left;color: #606060 !important">Book Sale</h3>

<p style="margin: 1em 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #606060;font-family: HelveticaNeue-Light, &quot;Helvetica Neue Light&quot;, &quot;Helvetica Neue&quot;, &quot;Trade Gothic W01 Light&quot;, Helvetica, Arial, &quot;Lucida Grande&quot;, sans-serif;font-size: 14px;line-height: 150%;text-align: left">The book sale will be held on <strong>Wednesday 16 October</strong> from 12:00 until 14:00. More information will be sent about this shortly. This year we will have an online system so will easily be able to see what's available in advance.</p>

<table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnDividerBlock" style="border-collapse: collapse;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%"><tbody class="mcnDividerBlockOuter"><tr><td class="mcnDividerBlockInner" style="padding: 10px 18px;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%">
                <table class="mcnDividerContent" border="0" cellpadding="0" cellspacing="0" width="100%" style="border-top-width: 1px;border-top-style: solid;border-top-color: #CCC;border-collapse: collapse;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%"><tbody><tr><td style="mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%">
                            <span></span>
                        </td>
                    </tr></tbody></table></td>
        </tr></tbody></table><h3 style="margin: 0;padding: 0;display: block;font-family: HelveticaNeue-Light, &quot;Helvetica Neue Light&quot;, &quot;Helvetica Neue&quot;, &quot;Trade Gothic W01 Light&quot;, Helvetica, Arial, &quot;Lucida Grande&quot;, sans-serif;font-size: 22px;font-style: normal;font-weight: 300;line-height: 125%;letter-spacing: -0.5px;text-align: left;color: #606060 !important">Experience a range of Interactive Demonstrations with BP on Monday</h3>

<p style="margin: 1em 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #606060;font-family: HelveticaNeue-Light, &quot;Helvetica Neue Light&quot;, &quot;Helvetica Neue&quot;, &quot;Trade Gothic W01 Light&quot;, Helvetica, Arial, &quot;Lucida Grande&quot;, sans-serif;font-size: 14px;line-height: 150%;text-align: left"><a href="http://bit.ly/1bGxQCP" style="word-wrap: break-word;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #6DC6DD;font-weight: normal;text-decoration: underline"><img src="https://eesoc.com/assets/email/uploads/email_1_2.jpg" width="550" style="width: 550px;border: 0;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;height: auto !important" /></a></p>

<table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnDividerBlock" style="border-collapse: collapse;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%"><tbody class="mcnDividerBlockOuter"><tr><td class="mcnDividerBlockInner" style="padding: 10px 18px;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%">
                <table class="mcnDividerContent" border="0" cellpadding="0" cellspacing="0" width="100%" style="border-top-width: 1px;border-top-style: solid;border-top-color: #CCC;border-collapse: collapse;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%"><tbody><tr><td style="mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%">
                            <span></span>
                        </td>
                    </tr></tbody></table></td>
        </tr></tbody></table><h3 style="margin: 0;padding: 0;display: block;font-family: HelveticaNeue-Light, &quot;Helvetica Neue Light&quot;, &quot;Helvetica Neue&quot;, &quot;Trade Gothic W01 Light&quot;, Helvetica, Arial, &quot;Lucida Grande&quot;, sans-serif;font-size: 22px;font-style: normal;font-weight: 300;line-height: 125%;letter-spacing: -0.5px;text-align: left;color: #606060 !important">Technology in Investment Banking Series with Deutsche Bank</h3>

<p style="margin: 1em 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #606060;font-family: HelveticaNeue-Light, &quot;Helvetica Neue Light&quot;, &quot;Helvetica Neue&quot;, &quot;Trade Gothic W01 Light&quot;, Helvetica, Arial, &quot;Lucida Grande&quot;, sans-serif;font-size: 14px;line-height: 150%;text-align: left">Where would modern investment banking be without the cutting edge technology that drives it? It's our GTO teams that have delivered some of the solutions that have had the biggest impact on our success. Within GTO, it's our analysis functions that help us translate our business's needs into technical specifications and then into the ground-breaking innovations that drive our business forward.</p>

<p style="margin: 1em 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #606060;font-family: HelveticaNeue-Light, &quot;Helvetica Neue Light&quot;, &quot;Helvetica Neue&quot;, &quot;Trade Gothic W01 Light&quot;, Helvetica, Arial, &quot;Lucida Grande&quot;, sans-serif;font-size: 14px;line-height: 150%;text-align: left">At the event you'll learn how technology is shaping the financial services industry and will get the chance to chat with Deutsche Bank employees at a wide range of levels. They will be happy to answer your questions and give you the insider's view of what a career in our technology division is really like. Event details are below.</p>

<p style="margin: 1em 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #606060;font-family: HelveticaNeue-Light, &quot;Helvetica Neue Light&quot;, &quot;Helvetica Neue&quot;, &quot;Trade Gothic W01 Light&quot;, Helvetica, Arial, &quot;Lucida Grande&quot;, sans-serif;font-size: 14px;line-height: 150%;text-align: left"><strong>Date:</strong> Thursday, 10th October 2013<br /><strong>Time:</strong> 6:30 - 8:30pm<br /><strong>Venue:</strong>  Imperial Campus, Physics LT2, Campus<br /><strong>Registration:</strong>  Please register your interest in attending the event by emailing <a href="mailto:imperial.events@db.com?subject=GTO Series Oct 10 RSVP" style="word-wrap: break-word;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #6DC6DD;font-weight: normal;text-decoration: underline">imperial.events@db.com</a> with email Subject: GTO Series Oct 10 RSVP<br /><strong>Questions?</strong> Email <a href="mailto:gsk10@ic.ac.uk" style="word-wrap: break-word;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #6DC6DD;font-weight: normal;text-decoration: underline">Giri</a>, one of our Industrial Liaison Officers and former DB Placement Student. </p>


<p style="margin: 1em 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #606060;font-family: HelveticaNeue-Light, &quot;Helvetica Neue Light&quot;, &quot;Helvetica Neue&quot;, &quot;Trade Gothic W01 Light&quot;, Helvetica, Arial, &quot;Lucida Grande&quot;, sans-serif;font-size: 14px;line-height: 150%;text-align: left">Please note this is the first of a 3-part series looking into Investment Banking technology. Students attending the session on Thursday will be invited to Part 2 which is going to be held at the Deutsche Bank offices in The City focusing on FX Trading.</p>

<table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnDividerBlock" style="border-collapse: collapse;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%"><tbody class="mcnDividerBlockOuter"><tr><td class="mcnDividerBlockInner" style="padding: 10px 18px;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%">
                <table class="mcnDividerContent" border="0" cellpadding="0" cellspacing="0" width="100%" style="border-top-width: 1px;border-top-style: solid;border-top-color: #CCC;border-collapse: collapse;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%"><tbody><tr><td style="mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%">
                            <span></span>
                        </td>
                    </tr></tbody></table></td>
        </tr></tbody></table><p style="margin: 1em 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #606060;font-family: HelveticaNeue-Light, &quot;Helvetica Neue Light&quot;, &quot;Helvetica Neue&quot;, &quot;Trade Gothic W01 Light&quot;, Helvetica, Arial, &quot;Lucida Grande&quot;, sans-serif;font-size: 14px;line-height: 150%;text-align: left">I hope you are as excited as the rest of the team and I are about the term we have coming up! We will be in touch soon so keep a look out for more EESoc emails!</p>

<p style="margin: 1em 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #606060;font-family: HelveticaNeue-Light, &quot;Helvetica Neue Light&quot;, &quot;Helvetica Neue&quot;, &quot;Trade Gothic W01 Light&quot;, Helvetica, Arial, &quot;Lucida Grande&quot;, sans-serif;font-size: 14px;line-height: 150%;text-align: left">With Best Wishes,</p>

<p style="margin: 1em 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #606060;font-family: HelveticaNeue-Light, &quot;Helvetica Neue Light&quot;, &quot;Helvetica Neue&quot;, &quot;Trade Gothic W01 Light&quot;, Helvetica, Arial, &quot;Lucida Grande&quot;, sans-serif;font-size: 14px;line-height: 150%;text-align: left">Thomas Lim<br />
EESoc President 2013/14</p>
                        </td>
                    </tr></tbody></table></td>
        </tr></tbody></table></td>
                                        </tr></table><!-- // END BODY --></td>
                            </tr><tr><td align="center" valign="top" style="mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%">
                                    <!-- BEGIN FOOTER // -->
                                    <table border="0" cellpadding="0" cellspacing="0" width="600" id="templateFooter" style="border-collapse: collapse;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;background-color: #FFF;border-top: 0;border-bottom: 0"><tr><td valign="top" class="footerContainer" style="padding-bottom: 9px;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%">
<table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnDividerBlock" style="border-collapse: collapse;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%"><tbody class="mcnDividerBlockOuter"><tr><td class="mcnDividerBlockInner" style="padding: 10px 18px;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%">
                <table class="mcnDividerContent" border="0" cellpadding="0" cellspacing="0" width="100%" style="border-top-width: 1px;border-top-style: solid;border-top-color: #CCC;border-collapse: collapse;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%"><tbody><tr><td style="mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%">
                            <span></span>
                        </td>
                    </tr></tbody></table></td>
        </tr></tbody></table><table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnTextBlock" style="border-collapse: collapse;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%"><tbody class="mcnTextBlockOuter"><tr><td valign="top" class="mcnTextBlockInner" style="mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%">

                <table align="left" border="0" cellpadding="0" cellspacing="0" width="600" class="mcnTextContentContainer" style="border-collapse: collapse;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%"><tbody><tr><td valign="top" class="mcnTextContent" style="padding-top: 9px;padding-right: 18px;padding-bottom: 9px;padding-left: 18px;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #606060;font-family: HelveticaNeue-Light, &quot;Helvetica Neue Light&quot;, &quot;Helvetica Neue&quot;, &quot;Trade Gothic W01 Light&quot;, Helvetica, Arial, &quot;Lucida Grande&quot;, sans-serif;font-size: 13px;line-height: 125%;text-align: left">

                            <div style="text-align: center;">
                                Sponsored by<br /><br /><img src="https://eesoc.com/assets/email/20131008/sponsors.png" width="500" height="139" style="width: 500px;height: auto !important;border: 0;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic" /></div>

                        </td>
                    </tr></tbody></table></td>
        </tr></tbody></table></td>
                                        </tr></table><!-- // END FOOTER --></td>
                            </tr></table><!-- // END TEMPLATE --></td>
                </tr><tr><td align="center" valign="top" id="bodyCell" style="mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;margin: 0;padding: 20px;border-top: 0;height: 100% !important;width: 100% !important;font-family: HelveticaNeue-Light, &quot;Helvetica Neue Light&quot;, &quot;Helvetica Neue&quot;, &quot;Trade Gothic W01 Light&quot;, Helvetica, Arial, &quot;Lucida Grande&quot;, sans-serif">








                        <table border="0" cellpadding="0" cellspacing="0" width="600" style="border-collapse: collapse;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;border-top: 0;border-bottom: 0"><tr><td valign="top" class="footerContainer" style="padding-bottom: 9px;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%">
<table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnTextBlock" style="border-collapse: collapse;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%"><tbody class="mcnTextBlockOuter"><tr><td valign="top" class="mcnTextBlockInner" style="mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%">

                <table align="left" border="0" cellpadding="0" cellspacing="0" width="600" class="mcnTextContentContainer" style="border-collapse: collapse;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%"><tbody><tr><td valign="top" class="mcnTextContent" style="padding-top: 9px;padding-right: 18px;padding-bottom: 9px;padding-left: 18px;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #606060;font-family: HelveticaNeue-Light, &quot;Helvetica Neue Light&quot;, &quot;Helvetica Neue&quot;, &quot;Trade Gothic W01 Light&quot;, Helvetica, Arial, &quot;Lucida Grande&quot;, sans-serif;font-size: 11px;line-height: 125%;text-align: left">

                            <div style="text-align: center;">
                                <i>Be social - stay in touch</i><br /><a href="http://on.fb.me/1fhTYE3" style="word-wrap: break-word;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #606060;font-weight: normal;text-decoration: underline"><img width="30" style="width: 30px;border: 0;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;height: auto !important" src="https://eesoc.com/assets/email/20131008/fb.png" /></a>    
                                <a href="http://bit.ly/16wDPG7" style="word-wrap: break-word;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #606060;font-weight: normal;text-decoration: underline"><img width="30" style="width: 30px;border: 0;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;height: auto !important" src="https://eesoc.com/assets/email/20131008/tw.png" /></a>    
                                <a href="http://bit.ly/16QRRVn" style="word-wrap: break-word;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #606060;font-weight: normal;text-decoration: underline"><img width="30" style="width: 30px;border: 0;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;height: auto !important" src="https://eesoc.com/assets/email/20131008/in.png" /></a>
                            </div>

                        </td>
                    </tr></tbody></table></td>
        </tr></tbody></table><table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnTextBlock" style="border-collapse: collapse;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%"><tbody class="mcnTextBlockOuter"><tr><td valign="top" class="mcnTextBlockInner" style="mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%">

                <table align="left" border="0" cellpadding="0" cellspacing="0" width="600" class="mcnTextContentContainer" style="border-collapse: collapse;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%"><tbody><tr><td valign="top" class="mcnTextContent" style="padding-top: 9px;padding-right: 18px;padding-bottom: 9px;padding-left: 18px;mso-table-lspace: 0;mso-table-rspace: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #606060;font-family: HelveticaNeue-Light, &quot;Helvetica Neue Light&quot;, &quot;Helvetica Neue&quot;, &quot;Trade Gothic W01 Light&quot;, Helvetica, Arial, &quot;Lucida Grande&quot;, sans-serif;font-size: 11px;line-height: 125%;text-align: left">

                            <div style="text-align: center;">
    <span style="text-align: center;"><a href="http://bit.ly/1a9ETgL" style="word-wrap: break-word;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #606060;font-weight: normal;text-decoration: underline">eesoc.com</a></span><br /><span style="text-align: center;"><a href="mailto:eesoc@imperial.ac.uk" style="word-wrap: break-word;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #606060;font-weight: normal;text-decoration: underline">eesoc@imperial.ac.uk</a></span></div>

                        </td>
                    </tr></tbody></table></td>
        </tr></tbody></table></td>
                                        </tr></table></td>
                </tr></table></center>
    </body>
</html>
